### ISSUE TITLE
Error: The redirect uri included is not valid.

### ISSUE THREAD

**Issue by jeff-matthews** [affinipay/app-integration-example-ruby#2]
Steps 2 in the README instructs me to use **http://localhost:9292/callback** as the redirect URI, but the redirect URI in the actual `env.rb` file uses my loopback interface (**http://127.0.0.1:9292/callback**). 

This causes the following error:
<img width="722" alt="error" src="https://cloud.githubusercontent.com/assets/13662379/24817518/6764592a-1ba2-11e7-8272-a8da9a714a14.png">

Changing the redirect URI in the `env.rb` file to match the URI in the AffiniPay OAuth app--as shown in step 3 of the README--resolves the issue.

**Comment by jwsparrow** [comment]
Steps 2 and 3 of the README should be updated to specify 127.0.0.1 (rather than localhost).
